Fix `--keep-dep-kinds` bug with multi-member workspaces (#127)
* `cargo tree` output from a `[workspace]` with multiple `members` will
  contain blank lines, causing `get_required_packages()` to choke.
* This fix just skips blank lines in `cargo tree` output.

To replicate the bug that was fixed:

(repo picked randomishly from multi-member workspaces found on GitHub)
```
git clone https://github.com/Macdu/vulkanite.git
cd vulkanite
cargo vendor-filterer --keep-dep-kinds no-dev ./vendor
```

Output from above prior to fix:
```
Gathering metadata
Skipping vulkanite
Skipping generator
Skipping example
error: Invalid output received from cargo tree:
```